### ISSUE TITLE
Set up code linter in fhir-react

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#11]
- [x] Set up eslint & prettier for fihr-react.
- [x] Add `lint` and `lint:fix` tasks to package.json that will check and automatically fix code formatting.
- [x] Fix the formatting and lint violations of the entire codebase.
- [x] Add the lint step to CircleCI build, so it will fail when code is malformed.

Recommended eslint config: see what create-react-app uses https://www.npmjs.com/package/eslint-config-react-app
https://www.npmjs.com/package/eslint-config-prettier
https://www.npmjs.com/package/eslint-plugin-prettier

Example .eslintrc config:

```
{
  "extends": [
    "react-app",
    "prettier"
  ],
  "plugins": [
    "prettier"
  ],
  "rules": {
    "semi": "error",
    "prettier/prettier": "error",
  }
}
```

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch;
