### ISSUE TITLE
Add R4 support to Organization component

### ISSUE THREAD

**Issue by ctomasz** [1uphealth/fhir-react#124]
TODO:

 - add R4 to Organization component

**Comment by liam1uphealth** [comment]
I think we should add a message to be dispayed if there is no data... in example R4, it should say 'No additional data' or something, otherwise it looks like it was an error on our part rather then the data simply not existing

**Comment by ctomasz** [comment]
@liam1uphealth I made changes related to your suggestion in the PR #172 ; please take a look.

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
