### ISSUE TITLE
Clean up package.json file in fihr-react

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#13]
- [x] Remove superfluous dependencies.
- [x] Add scripts field for common tasks (lint, test, build).

**Comment by tp1uphealth** [comment]
> - [x] Remove superfluous dependencies.

Done in #18 

> - [x] Add scripts field for common tasks (lint, test, build).

All of these tasks were added in previous issues 👍

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch;
