### ISSUE TITLE
Round Observation Values

### ISSUE THREAD

**Issue by kyle1uphealth** [1uphealth/fhir-react#214]
The values of Observation values should be rounded

<img width="1166" alt="Screen Shot 2020-08-11 at 1 25 10 PM" src="https://user-images.githubusercontent.com/55711798/89928641-1cbf3a00-dbd6-11ea-9aac-275b31928143.png">

Default to 2 decimal places
`Potassium 4.723390524519659mmol/L`

Should be `Potassium 4.72 mmol/L`

Except Specific gravity of Urine by Test strip, round to 3 decimal places.

Ideally also include ability to specify how many digits to round a given test.

**Comment by ctomasz** [comment]
I created PR to those changes https://github.com/1uphealth/fhir-react/pull/216
I updated Storybook as well - http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/?path=/story/observation--example-2-of-r-4
