### ISSUE TITLE
Make references between Resources Name instead of ID

### ISSUE THREAD

**Issue by kyle1uphealth** [1uphealth/fhir-react#215]
For example, under Observation Resource component, it should be `SUBJECT John Doe Patient/03fb4e85a167` instead of just `SUBJECT Patient/03fb4e85a167`. This will make the information more helpful to the end user, who doesn't get any meaning from the ID alone.

Other references:
- [ ] AllergyIntolerance PATIENT
- [ ] Observation SUBJECT
- [ ] ExplanationOfBenefit CLAIM PROVIDER, PATIENT
- [ ] Coverage ISSUER
- [ ] Other resource types with references

<img width="1172" alt="Screen Shot 2020-08-11 at 1 29 16 PM" src="https://user-images.githubusercontent.com/55711798/89929035-abcc5200-dbd6-11ea-9167-75148ea6717a.png">

**Comment by ctomasz** [comment]
@sanjay1uphealth Would you past here a source of resource (if you click at the "JOSN" button, then the source of a resource should be displayed)? 
It will be helpful for us in find out some solution for this issue.

**Comment by sanjay1uphealth** [comment]
@ctomasz great question, I am assuming yes. Let me quickly check with Kyle and get back to you. Thanks !

**Comment by kyle1uphealth** [comment]
For example this allergy below, however the problem is ideally we want to show the patient name, not just the patient ID, but the name itself doesn't live in this allergy resource, it lives in the referenced Patient resource. Not sure if this is feasible/doable or if you have ideas how to efficiently pull data across related resources (allergy pulling from patient)
`{
  "identifier": [
    {
      "system": "https:fhir-myrecord.sandboxcerner.com",
      "value": "7655753"
    }
  ],
  "recorder": {
    "reference": "Practitioner/106df201122207064dc18dca",
    "display": "Generated Domain User for 0"
  },
  "recordedDate": "2017-02-28T21:03:00.000Z",
  "substance": {
    "coding": [
      {
        "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
        "code": "10831",
        "userSelected": false,
        "display": "Sulfamethoxazole / Trimethoprim"
      }
    ],
    "text": "sulfamethoxazole-trimethoprim"
  },
  "criticality": "CRITL",
  "onset": "2015-12-14T18:00:00.000-06:00",
  "type": "allergy",
  "meta": {
    "lastUpdated": "2019-12-30T21:00:21.947Z",
    "versionId": "9000000000002"
  },
  "patient": {
    "reference": "Patient/106df2011222"
  },
  "id": "106df201122209cf5caa0372d9b937fbc8944e360f4bcb3f",
  "text": {
    "div": "<div><p><b>Allergy Intolerance</b></p><p><b>Patient</b>: Smart, Barney R</p><p><b>Allergy</b>: sulfamethoxazole-trimethoprim</p><p><b>Status</b>: Active</p><p><b>Criticality</b>: Low Risk</p><p><b>Category</b>: Medication</p><p><b>Onset</b>: Dec 15, 2015 12:00 A.M. UTC</p></div>",
    "status": "generated"
  },
  "category": "medication",
  "resourceType": "AllergyIntolerance",
  "status": "active"
}`

**Comment by kyle1uphealth** [comment]
It appears sometimes (like example above) the patient name will live in the "text": field but not always

**Comment by ctomasz** [comment]
Thanks Kyle. This is it what I wanted to confirm - that real resource does not contain the name of the patient (the only reference to her profile/details).

Once we discussed possible solutions that could be helpful in this case, we'll back to you.

**Comment by KonradNojman** [comment]
Ok, thanks. 
Do we need to do anything else regarding this issue, or can we close it for now @kyle1uphealth ?

**Comment by kyle1uphealth** [comment]
Yes can close for now. Thanks all
