### ISSUE TITLE
Deploy storybook to an accessible URL

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#23]
TODO:

- Build storybook to a static bundle on CircleCI (on master branch)
- Deploy the bundle to a public URL (e.g. AWS S3, GitHub pages etc...)

**Comment by ctomasz** [comment]
Status:
 - Storybook URL: http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/
 - the procedure of building the static pages of Storybook and do deploy to AWS S3 is handled via` "npm command" for now

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch;
