### ISSUE TITLE
STU3 support for Condition component

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#24]
TODO:

- Add STU3 support to Condition component
- Add fixtures, tests, storybook stories

**Comment by tp1uphealth** [comment]
Started this work on https://github.com/1uphealth/fhir-react/compare/24-condition-stu3 branch.

**Comment by tp1uphealth** [comment]
The `Condition` resource component was updated.

Storybook URL: http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/?path=/story/condition--default-visualization-dstu-2

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
