### ISSUE TITLE
Analyze which Must Support elements for CARIN BB resources are missing from react components

### ISSUE THREAD

**Issue by kyle1uphealth** [1uphealth/fhir-react#247]
### Background:

- We'd like to assess the difference between what the react components for CARIN BB resources currently display relative to the "Must Support" data elements (attributes) defined by the CARIN BB Implementation Guide
- For the resources with links below, create a simple analysis (spreadsheet or otherwise) that highlights what the react components currently display, and which Must Support Attributes are missing.

For example for Coverage these are the Must support elements from this page: https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Coverage.html 

![image](https://user-images.githubusercontent.com/55711798/127496815-f4f029b8-76b7-4d8c-8285-300835a929f1.png)

Resources to assess:

- [ ] Coverage https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Coverage.html
- [ ] EOB Inpatient https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-ExplanationOfBenefit-Inpatient-Institutional.html
- [ ] EOB Outpatient https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-ExplanationOfBenefit-Outpatient-Institutional.html
- [ ] EOB Pharmacy https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-ExplanationOfBenefit-Pharmacy.html
- [ ] EOB Professional https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-ExplanationOfBenefit-Professional-NonClinician.html
- [ ] Organization - https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Organization.html
- [ ] Patient - https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Patient.html
- [ ] Practitioner - https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-Practitioner.html

**Comment by KonradNojman** [comment]
@kyle1uphealth based on the [Available resources](https://github.com/1uphealth/fhir-react#available-resources) table only EOB currently supports CarinBB profile (I'll check different flavors from the checklist later).
But now I can tell you that `Coverage`, `Organization`, `Patient` and `Practitioner` don't support CarinBB. If this is something we will need, we can create tickets for it and roughly assess the timeline (or decide on the next sprint planning session depending on priority)

**Comment by kyle1uphealth** [comment]
Thanks @KonradNojman - so does that mean for EOB that the react component displays all of these Must Support elements? Does it vary depending on if it's inpatient vs outpatient vs pharmacy EOB?
![image](https://user-images.githubusercontent.com/55711798/127505040-e1861447-4b9b-45f7-97e4-011b99d2cc89.png)

**Comment by KonradNojman** [comment]
@kyle1uphealth the fields supported in EOB right now were taken from [https://github.com/1uphealth/1up-fhir-test-app/issues/41](https://github.com/1uphealth/1up-fhir-test-app/issues/41)
There is no differentiation between different EOB flavors right now (inpatient/outpatient/pharmacy).

## The fields we currently support

### From regular HL7 specs for R4:

- disposition
- created
- insurer
- type.coding
- status
- use
- patient
- provider
- total
- item
    - category
    - productOrService
    - servicedDate
    - servicedPeriod
    - locationAddress
    - locationCodeableConcept
    - locationReference
    - encounter
    - net
    - adjudication
- supportingInfo
    - sequence
    - category
    - code
    - timingDate
    - timingPeriod.start
    - timingPeriod.end
- insurance
- coverage

### And additionally from the CarinBB profile:

- diagnosis
- payment.amount
- billablePeriod
- identifier
- outcome
- careTeam
- payee.type
- payee.party
- related

## What we don't support now (based on the [EOB Inpatient Institutional](https://build.fhir.org/ig/HL7/carin-bb/StructureDefinition-C4BB-ExplanationOfBenefit-Inpatient-Institutional.html) that you've linked):

- meta
- subType
- procedure
- adjucation
- payment
    - type
    - date
- processNote

**Comment by kyle1uphealth** [comment]
Can you do a similar analysis for the `What we don't support now` based on the `Resources to assess:` in the original issue content above?

**Comment by KonradNojman** [comment]
@kyle1uphealth I've added info for all mentioned components in this Notion page
https://www.notion.so/1uphealth/CarinBB-support-table-for-fhir-react-components-deb8f3eb6e5f46b3a2c9bdc1ae05b9e2

Please let me know if you have access to it and have any questions 🙂

**Comment by KonradNojman** [comment]
@kyle1uphealth can we close this ticket? Is there anything else to do here?
