### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dwwinters** [1uphealth/fhir-react#376]
### Background:

I'd really like to incorporate this project into a dashboard I'm working on, but your package.json [specifies a non-commericial license](https://github.com/1uphealth/fhir-react/blob/main/package.json#L61).  Before I go implement my own solution I'd just like to confirm the license for this project and that what's in the package.json isn't a mistake.

### Expected Behavior:

n/a

### Screenshots:

n/a

**Comment by tony1uphealth** [comment]
Hello - yes, I can confirm that the license in the package.json is the intended and correct license: https://creativecommons.org/licenses/by-nc-sa/4.0/
