### ISSUE TITLE
What is the license on this repository?

### ISSUE THREAD

**Issue by ahmetsevki** [1uphealth/fhir-react#396]
### Background:

- The repository does not have a LICENSE document, so it is hard to know if one can use / fork it.

### Expected Behavior:

a LICENSE document that lists one of the standard licenses that people can understand.

**Comment by jocelynn1uphealth** [comment]
@ahmetsevki - hey I have a [PR](https://github.com/1uphealth/fhir-react/pull/403) up to add an MIT license to this, so feel free to use, thanks for the call out!

**Comment by jocelynn1uphealth** [comment]
PR #403 was merged
