### ISSUE TITLE
create DocumentReference component

### ISSUE THREAD

**Issue by ctomasz** [1uphealth/fhir-react#63]
TODO:
 - Create scaffold of component
 - Add DSTU2 support to component
 - Add STU3 support to component
 - Add fixtures, tests, storybook stories

**Comment by tp1uphealth** [comment]
Done in #73 

Storybook: http://storybook-fhir-react-lib.s3-website-us-east-1.amazonaws.com/?path=/story/document-reference--example-stu-3

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
