### ISSUE TITLE
Remove dead code from fhir-react

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#71]
I noticed the current size of `fhir-react` package is ~430KB (uncompressed).
This is way too big for a reusable package.

AFAICT, the main culprits are:
- `lodash` package, which is being imported in entirety, even though we use only a few utilities.
- `crypto` package, also imported whole even though we just use the MD5 hash function.

TODO:
- [x] Replace `lodash` imports with imports of individual utilities, e.g. `lodash/get`.
  Bonus: make sure lodash is never imported whole, for example using https://www.npmjs.com/package/babel-plugin-transform-imports.
- [x] Find a more lightweight alternative for `crypto` package.

**Comment by tp1uphealth** [comment]
> - [x] Replace `lodash` imports with imports of individual utilities, e.g. `lodash/get`.
>   Bonus: make sure lodash is never imported whole, for example using  https://www.npmjs.com/package/babel-plugin-transform-imports.
> - [x] Find a more lightweight alternative for `crypto` package.

Both done in #82 . `crypto` package was replaced with `md5`.

End result was ~81% reduction in total bundle size.

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
