### ISSUE TITLE
Improve the style architecture

### ISSUE THREAD

**Issue by tp1uphealth** [1uphealth/fhir-react#78]
The current state of styling in `fhir-react` is a mix of inline styles and bootstrap.
It is not very readable, a bit inconsistent and not extensible by users.

Here's our idea to improve the architecture:
- Consistency: write regular CSS files for styles, instead of inline/bootstrap combo.
- Extensibility: use BEM-style class names e.g. `.fhir-ui__Value`, `fhir-resource__Observation`. Consumers will be able to override these classes with their own styles.
- Lessen the dependency on bootstrap (avoid using its classes and utilities).

TODO:

- [x] Style components in `src/components/ui`
- [x] Style components in `src/components/resources`
- [x] Style components in `src/components/container`
- [x] Style components in `src/components/datatypes`
- [x] Optional: export one stylesheet for consumers to import (e.g. via webpack)

**Comment by tp1uphealth** [comment]
> - [x] Style components in `src/components/ui`
> - [x] Style components in `src/components/resources`
> - [x] Style components in `src/components/container`
> - [x] Style components in `src/components/datatypes`

This was done jointly in #79 

> - [x] Optional: export one stylesheet for consumers to import (e.g. via webpack)

Done in #80

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
