### ISSUE TITLE
create Medication component

### ISSUE THREAD

**Issue by ctomasz** [1uphealth/fhir-react#93]
TODO:
- Create scaffold of component
- Add DSTU2 support to component
- Add STU3 support to component
- Add fixtures, tests, storybook stories

**Comment by liam1uphealth** [comment]
I'm going to move this component to "done" in the story board, and I believe we talked about this before but this component is an example where I think padding/margin below headers is too large. We don't want components to become to large

**Comment by ctomasz** [comment]
Required changes merged into the `master` branch; The functionality available at `fhir-react` library from `0.1.2` version;
